# **read different data files**

**the html5lib package, which is required for certain HTML parsing operations.**

# press shift enter for to get more information about your code

In [2]:
pip install html5lib

Requirement already satisfied: html5lib in c:\users\genai\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\genai\anaconda3\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\genai\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Note: you may need to restart the kernel to use updated packages.

## *read json file*<be>
JSON stands for JavaScript Object Notation. <br>
JSON is a text format for storing and transporting data. JSON is "self-describing" and easy to understand.<br>

In [3]:
# first_method
# Load the JSON file
import json
with open('fruits_data.json') as file:
    data = json.load(file)

In [8]:
data

{'fruits': [{'name': 'Apple',
   'color': 'Red',
   'taste': 'Sweet',
   'season': 'Fall',
   'nutrients': ['Vitamin C', 'Fiber']},
  {'name': 'Banana',
   'color': 'Yellow',
   'taste': 'Sweet',
   'season': 'Year-round',
   'nutrients': ['Potassium', 'Vitamin B6']},
  {'name': 'Orange',
   'color': 'Orange',
   'taste': 'Citrus',
   'season': 'Winter',
   'nutrients': ['Vitamin C', 'Fiber']},
  {'name': 'Strawberry',
   'color': 'Red',
   'taste': 'Sweet',
   'season': 'Spring',
   'nutrients': ['Vitamin C', 'Manganese']},
  {'name': 'Blueberry',
   'color': 'Blue',
   'taste': 'Sweet',
   'season': 'Summer',
   'nutrients': ['Vitamin C', 'Vitamin K']}]}

In [12]:
import pandas as pd

## *read HTML file*<be>

In [13]:

Minnesota = pd.read_html('https://en.wikipedia.org/wiki/Minnesota')

# Display the number of tables
len(Minnesota)

HTTPError: HTTP Error 403: Forbidden

In [17]:
# we want table 2 to be returned

df = Minnesota[2]
df

  Largest cities or towns in Minnesota Source:[83]                          \
                                              Rank         Name     County
0                                                1  Minneapolis   Hennepin
1                                                2   Saint Paul     Ramsey
2                                                3    Rochester    Olmsted
3                                                4  Bloomington   Hennepin
4                                                5       Duluth  St. Louis

                                                                    \
     Pop. Unnamed: 4_level_1 Unnamed: 5_level_1 Unnamed: 6_level_1
0  425336                NaN                NaN                NaN
1  307193                NaN                NaN                NaN
2  121465                NaN                NaN                NaN
3   89298                NaN                NaN                NaN
4   86372                NaN                NaN                NaN


  Unnamed: 7_level_1 Unnamed: 8_level_1 Unnamed: 9_level_1
0                NaN                NaN                NaN
1                NaN                NaN                NaN
2                NaN                NaN                NaN
3                NaN                NaN                NaN
4                NaN                NaN                NaN

# read tabular files

In [5]:
# first, import the library pandas - run this cell before the next ones, as it imports pandas.
import pandas as pd

### press Tab to auto-complete file names or commands.

In [14]:
#since the file is csv, we use pd.read_csv
test = pd.read_csv('student_test.csv')

In [17]:
#show the first five rows of the dataset
test.head()

,id,Timestamp,Entering Grade Level,District,Overall Score,School Preferences,School Assigned,Will you enroll there?
0,1,4/08/2017 6:44,1,6.0,99,"NEST+m, TAG, Anderson, Q300",NEST,YES
1,2,4/07/2017 10:40,K,NaN,99,"Anderson, NEST+m",NaN,Maybe
2,3,4/07/2017 10:41,1,NaN,98,NaN,NaN,Maybe
3,4,4/07/2017 10:43,K,NaN,98,NaN,NaN,NaN
4,5,4/10/2017 10:18,K,22.0,99,Brooklyn School of Inquiry,Currently - local Brooklyn dual language,Maybe

In [ ]:
# shows the last five rows of the dataset
test.tail()

In [ ]:
#can adjust to display the first n rows of the dataframe. 
test.head(2)

In [ ]:
#can adjust to display the last n rows of the dataframe. 
test.tail(2)

In [ ]:
# only select a column or columns of the dataset
dataset_name['column_name']
datset_name[['column_names spetared by ,']]

In [26]:
test['Timestamp']

0           4/08/2017 6:44
1          4/07/2017 10:40
2          4/07/2017 10:41
3          4/07/2017 10:43
4          4/10/2017 10:18
              ...
112     6/20/2017 16:06:54
113     6/21/2017 22:52:59
114     9/14/2017 16:39:55
115    11/19/2017 17:07:05
116        1/11/2019 15:03
Name: Timestamp, Length: 117, dtype: object

In [18]:
#display a summary of the dataframe, including the range index, dtypes, column headers, and memory usage
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      117 non-null    int64
 1   Timestamp               117 non-null    object
 2   Entering Grade Level    117 non-null    object
 3   District                101 non-null    float64
 4   Overall Score           117 non-null    int64
 5   School Preferences      75 non-null     object
 6   School Assigned         28 non-null     object
 7   Will you enroll there?  71 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 7.4+ KB

The columns with text are by default marked as Object datatype.<br>
But Object dtype have a much broader scope. They can not only include strings, but also any other data that Pandas doesn't understand.

Every data type in Python (such as integers, floats, strings, lists, dictionaries, etc.) inherits from object.when python cannot detect the exact data type, it labels it as objetc

# convert data types

df referes to dataframe or the dataset that we imported - it is a default phrase, in our case the dataset is called test

In [ ]:
# Option 1: Works with missing values (NaN)
df['column_name'] = df['column_name'].astype('Int64')

# Option 2: Only works if there are NO missing values
df['column_name'] = df['column_name'].astype('int64')

In [55]:
# since we have missing values in the column district, we use the first method
test['District'] = test['District'].astype('Int64')

In [19]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      117 non-null    int64
 1   Timestamp               117 non-null    object
 2   Entering Grade Level    117 non-null    object
 3   District                101 non-null    float64
 4   Overall Score           117 non-null    int64
 5   School Preferences      75 non-null     object
 6   School Assigned         28 non-null     object
 7   Will you enroll there?  71 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 7.4+ KB

**describe()**

method will return descriptive statistics of the entire dataset, including total count, mean, minimum, maximum, dispersion, and distribution.<br>
<font color='red'>why the below code doesn't it show the statistical description for the rest of the columns?</font>

In [29]:
test.describe()

               id    District  NNAT Non Verbal Percentile  Overall Score
count  117.000000  101.000000                  117.000000     117.000000
mean    59.000000   12.504950                   98.632479      97.324786
std     33.919021   11.406686                    1.393323       3.784790
min      1.000000    1.000000                   90.000000      70.000000
25%     30.000000    2.000000                   99.000000      97.000000
50%     59.000000    3.000000                   99.000000      99.000000
75%     88.000000   25.000000                   99.000000      99.000000
max    117.000000   32.000000                   99.000000      99.000000

**shape**  representing the dimensions of the dataframe **by number of rows and columns**.<br>
Attributes are not followed by parentheses. to recap:<br>
Attributes are variables that are associated with an object or class. They represent the state or data of the object.<br>
Functions are blocks of code that perform a specific task and can be defined within a class or independently.<br>

In [31]:
test.shape

(117, 13)

**The panda's conversion function to date time convert our date column to DateTime,** which will split up the date objects into separate data points of year, month, and day.

In [29]:
#access a column in your dataframe
test['Timestamp']

0           4/08/2017 6:44
1          4/07/2017 10:40
2          4/07/2017 10:41
3          4/07/2017 10:43
4          4/10/2017 10:18
              ...
112     6/20/2017 16:06:54
113     6/21/2017 22:52:59
114     9/14/2017 16:39:55
115    11/19/2017 17:07:05
116        1/11/2019 15:03
Name: Timestamp, Length: 117, dtype: object

In [43]:
#panda's conversion function to date time convert our date column to DateTime
test['date'] = pd.to_datetime(test['Timestamp'], format='mixed')

#pd.to_datetime(): Converts a column to datetime format.
#test_results['Timestamp']: The column containing timestamp data that needs conversion.
#format='mixed': This allows pandas to automatically detect and parse different datetime formats in the column, handling inconsistencies.

In [37]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          117 non-null    int64
 1   Timestamp                   117 non-null    object
 2   Entering Grade Level        117 non-null    object
 3   District                    101 non-null    float64
 4   Birth Month                 117 non-null    object
 5   OLSAT Verbal Score          117 non-null    object
 6   OLSAT Verbal Percentile     117 non-null    object
 7   NNAT Non Verbal Raw Score   117 non-null    object
 8   NNAT Non Verbal Percentile  117 non-null    int64
 9   Overall Score               117 non-null    int64
 10  School Preferences          75 non-null     object
 11  School Assigned             28 non-null     object
 12  Will you enroll there?      71 non-null     object
 13  date                        117 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(9)
memory usage: 12.9+ KB

In [45]:
# Extract the year part and create a new column 'year'
test['year'] = test['date'].dt.year

In [47]:
# create month
test['month'] = test['date'].dt.month

In [73]:
test.head(2)

,id,Timestamp,Entering Grade Level,District,Birth Month,OLSAT Verbal Score,OLSAT Verbal Percentile,NNAT Non Verbal Raw Score,NNAT Non Verbal Percentile,Overall Score,School Preferences,School Assigned,Will you enroll there?,date,year,month
0,1,4/08/2017 6:44,1,6.0,September,28,99,45,99,99,"NEST+m, TAG, Anderson, Q300",NEST,YES,2017-04-08 06:44:00,2017,4
1,2,4/07/2017 10:40,K,NaN,August,25,99,39,99,99,"Anderson, NEST+m",NaN,Maybe,2017-04-07 10:40:00,2017,4

##  The nunique() method returns the number of unique values for each column.

By specifying the column axis (axis='columns'), the nunique() method searches column-wise and returns the number of unique values for each row.

In [173]:
unique_values = test_results['year'].unique()
print(unique_values)

[2017 2019]

In [57]:
nunique_values = test_results['year'].nunique()
print(nunique_values)

2

# important: unique and value counts help us find wrong entries and unclean data

In [ ]:
value_counts = test['year'].value_counts()
print(value_counts)

# Important! Save the clean file back to your home directory

In [ ]:
#save the files back into directory/folder
# index=False means do not create a column for indexing
test.to_csv('test_clean.csv', index=False)