In [30]:
import pandas as pd
test = pd.read_csv('samsung_sales_data.csv')

In [31]:
test.head(3)

   OrderID          Product     Category  Quantity  Price  OrderDate
0        1  Galaxy Buds Pro  Accessories      74.0  32.85  1/01/2023
1        2   Galaxy Watch 4    Wearables      17.0  90.15  2/01/2023
2        3   Galaxy Watch 4    Wearables      84.0   6.24  3/01/2023

In [32]:
test.tail(3)

     OrderID          Product     Category  Quantity  Price   OrderDate
497      498  Galaxy Buds Pro  Accessories      54.0  54.38  12/05/2024
498      499    Galaxy Tab S7      Tablets      85.0  37.02  13/05/2024
499      500  Galaxy Buds Pro  Accessories       NaN  83.74  14/05/2024

# Data Schema Information
- The sample data has 6 columns with 500 entries
- Some values are missing in columns Quantity and Price
- Some values have wrong data type like the Product, Category, OrderDate

In [33]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    500 non-null    int64
 1   Product    500 non-null    object
 2   Category   500 non-null    object
 3   Quantity   475 non-null    float64
 4   Price      475 non-null    float64
 5   OrderDate  500 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 23.6+ KB

In [13]:
test['Product'] = test['Product'].astype('string')

In [14]:
test['Category'] = test['Category'].astype('string')

In [16]:
test['OrderDate'] = pd.to_datetime(test['OrderDate'], format='mixed')

In [29]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    500 non-null    int64
 1   Product    500 non-null    string
 2   Category   500 non-null    string
 3   Quantity   475 non-null    float64
 4   Price      475 non-null    float64
 5   OrderDate  500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), string(2)
memory usage: 23.6 KB

In [19]:
products = test['Product'].unique()
category = test['Category'].unique()

In [25]:
len(category)

4

In [28]:
len(products)

5

In [37]:
value_counts = products.value_counts()
print(value_counts)

Galaxy Buds Pro    1
Galaxy Watch 4     1
Galaxy Tab S7      1
Galaxy S21         1
Galaxy Note 20     1
Name: count, dtype: Int64

In [36]:
value_counts = test['Category'].value_counts()
print(value_counts)

Category
Smartphones    178
Wearables      111
Tablets        110
Accessories    101
Name: count, dtype: int64

In [40]:
columns = test.columns
for col in columns:
    print(f"{col}: {test[col].nunique()} unique values")

OrderID: 500 unique values
Product: 5 unique values
Category: 4 unique values
Quantity: 98 unique values
Price: 460 unique values
OrderDate: 500 unique values